export const headCells = [
  // {
  //   id: 'no',
  //   numeric: false,
  //   disablePadding: false,
  //   label: 'No',
  //   width: 10,
  // },
  {
    id: 'contract_address',
    numeric: false,
    disablePadding: false,
    label: 'Contract Address',
    width: 10,
  },
  {
    id: 'name',
    numeric: false,
    disablePadding: false,
    label: 'Name',
    width: 10,
  },
  {
    id: 'description',
    numeric: false,
    disablePadding: false,
    label: 'Description',
    width: 10,
  },
  {
    id: 'collection',
    numeric: false,
    disablePadding: false,
    label: 'Collection',
    width: 10,
  },
  {
    id: 'sellingQuantity',
    numeric: false,
    disablePadding: false,
    label: 'Selling Quantity',
    width: 10,
  },
  {
    id: 'creator',
    numeric: false,
    disablePadding: false,
    label: 'Creator',
    width: 10,
  },
  {
    id: 'status',
    numeric: false,
    disablePadding: false,
    label: 'Status',
    width: 10,
  },
  {
    id: 'selling',
    numeric: false,
    disablePadding: false,
    label: 'Selling',
    width: 10,
  },
  {
    id: 'saleDate',
    numeric: false,
    disablePadding: false,
    label: 'Sale Date',
    width: 10,
  },
  {
    id: 'createdAt',
    numeric: false,
    disablePadding: false,
    label: 'Created at',
    width: 10,
  },
  {
    id: 'actions',
    numeric: false,
    disablePadding: false,
    label: 'Actions',
    width: 10,
  },
];
